version: '3.3'
secrets:
  TOKEN:
    external:
      name: RenamerToken
  MEMBER_ID:
    external:
      name: RenamerClientId
  GUILD_ID:
    external:
      name: RenamerGuildId
services:
  bot:
    image: ghcr.io/cox5529/discord-narrator:latest
    build:
      context: .
      dockerfile: Dockerfile
    secrets:
      - TOKEN
      - GUILD_ID
      - MEMBER_ID
